apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-pod
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis-pod
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32002
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
spec:
  type: NodePort
  selector:
    app: redisinsight-pod
  ports:
  - port: 5540
    targetPort: 5540
    nodePort: 32001

